apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-05-30T09:14:55Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "2703"
  uid: b917e35e-f15d-48ec-ac0b-84169330203d
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.104.77.196
  clusterIPs:
  - 10.104.77.196
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31633
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
